services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: spinner
      POSTGRES_PASSWORD: longirostris
      POSTGRES_DB: stenella
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://spinner:longirostris@db:5432/stenella
    depends_on:
      - db
    volumes:
      - .:/app  # Hot-reloading: changes in code reflect in the container

volumes:
  postgres_data:
