"""Add UserActivity table

Revision ID: 3a1c6e414b93
Revises: b0f9565ba203
Create Date: 2026-02-20 10:29:43.972530

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "3a1c6e414b93"
down_revision = 'b0f9565ba203'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useractivity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useractivity_date'), 'useractivity', ['date'], unique=False)
    op.create_index(op.f('ix_useractivity_user_id'), 'useractivity', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useractivity_user_id'), table_name='useractivity')
    op.drop_index(op.f('ix_useractivity_date'), table_name='useractivity')
    op.drop_table('useractivity')
    # ### end Alembic commands ###
