"""Add EmailDailyLog

Revision ID: 426d020bf1a0
Revises: ec8bb93f0c98
Create Date: 2026-03-03 08:30:21.229808

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "426d020bf1a0"
down_revision = 'ec8bb93f0c98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emaildailylog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'date', name='uix_email_date')
    )
    op.create_index(op.f('ix_emaildailylog_date'), 'emaildailylog', ['date'], unique=False)
    op.create_index(op.f('ix_emaildailylog_email'), 'emaildailylog', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emaildailylog_email'), table_name='emaildailylog')
    op.drop_index(op.f('ix_emaildailylog_date'), table_name='emaildailylog')
    op.drop_table('emaildailylog')
    # ### end Alembic commands ###
