"""Add tier field to User

Revision ID: 58526d19487d
Revises: c7d2e8f9a1b3
Create Date: 2026-04-08 23:16:40.654856

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "58526d19487d"
down_revision = 'c7d2e8f9a1b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), server_default='FREE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tier')
    # ### end Alembic commands ###
