"""reset_db

Revision ID: b0f9565ba203
Revises: e2c505ff40eb
Create Date: 2026-02-19 05:10:47.749323

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "b0f9565ba203"
down_revision = 'e2c505ff40eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
