"""Add UniqueConstraint to UserActivity table

Revision ID: ec8bb93f0c98
Revises: 3a1c6e414b93
Create Date: 2026-02-20 10:31:48.127119

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "ec8bb93f0c98"
down_revision = '3a1c6e414b93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_id_date', 'useractivity', ['user_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_id_date', 'useractivity', type_='unique')
    # ### end Alembic commands ###
